# Site settings
title: Explore
description: "Welcome to Wythe space."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "rxjyue.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Wythe Space
user_title: Wythe
email: zj107xx@gamil.com
#twitter_username: loremipsum
github_username:  loremipsum
#discord_invite: cj5rg # Example: Discord server invite gg extension like in 'https://discord.gg/cj5rg'
#linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
#profile_picture: https://as2.ftcdn.net/v2/jpg/04/83/90/95/1000_F_483909569_OI4LKNeFgHwvvVju60fejLd9gj43dIcd.jpg
profile_picture: https://upload.wikimedia.org/wikipedia/commons/f/f6/Leibniz%27s_drawing_of_his_calculating_machine.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: content
      url: /posts
      key_trigger: Featured
    #- title: series
      #url: /series
      #key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: me
      url: /about
      key_trigger: About
  section_2:
    - title: github
      url: http://www.github.com/victorvoid
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/victorvoid
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: wbdxxsdwldthzs72hrs
    url: https://github.com/RXJyue
  - name: ABOUND analysis
    url: https://www.corporate.carrier.com/abound/
  - name: Air conditioning units remote processing based on LAN & Wi-Fi(PDP processing)
    url: https://www.se.com/us/en/faqs/FA168406/#:~:text=Modbus%20is%20a%20serial%20communication,serial%20lines%20between%20electronic%20devices.

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
